language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-coverage
    - python: 3.6
      env: TOXENV=py36-coverage
    - python: 3.7
      env: TOXENV=py37-coverage

install: pip install tox

script: tox

after_success:
  - curl -S -L --connect-timeout 5 --retry 6 -s https://codecov.io/bash -o codecov-upload.sh
  - bash codecov-upload.sh -Z -X fix -f coverage.xml
