language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

install: pip install tox-travis coveralls

script: tox

after_success:
  - tox -e coverage-report
  - coveralls
